name: Build EDK2 Firmware

on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Error: The version '2.x' with architecture 'x64' was not found for Ubuntu 22.04.
          # python-version: '2.x'
          python-version: '3.x'
          cache: 'pip'
          
      - name:  Run build.sh
        run: |
          bash build.sh
          exit 0
