name: Build EDK2 Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.x'
          cache: 'pip'
          
      - name:  Run build.sh
        run: |
          bash build.sh
